# Dependencies
plugins:
  - jekyll-sitemap
  - jekyll-email-protect

# File rules
exclude:
  # default excludes
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # custom excludes
  - .gitignore
  - Makefile
  - LICENSE
  - README.md
  - assets/
  - package.json
  - package-lock.json
  - scripts/
  - .github/
  - .nova/

include:
  - .htaccess
  # bootstrap js + popper
  - node_modules/bootstrap/dist/js/bootstrap.bundle.min.js
  - node_modules/bootstrap/dist/js/bootstrap.bundle.min.js.map
  # bootstrap icons
  - node_modules/bootstrap-icons/font/bootstrap-icons.css
  - node_modules/bootstrap-icons/font/fonts/bootstrap-icons.woff
  - node_modules/bootstrap-icons/font/fonts/bootstrap-icons.woff2

keep_files:
  - .well-known

# Site
permalink: /blog/:year/:month/:day/:title/
excerpt_separator: <!--excerpt-->

# jekyll-sass-converter
# https://github.com/jekyll/jekyll-sass-converter?tab=readme-ov-file#configuration-options
sass:
  style: compressed
  quiet_deps: true
  # Silence various deprecation warnings from Bootstrap.
  # This is a known issue and will likely be resolved in v6.
  #
  # See the following issues:
  #   - https://github.com/twbs/bootstrap/issues/41915
  #   - https://github.com/twbs/bootstrap/issues/40962
  #   - https://github.com/twbs/bootstrap/issues/40849
  #
  # Sass Docs:
  #   https://sass-lang.com/documentation/breaking-changes/import/
  silence_deprecations: ['import', 'if-function', 'global-builtin', 'color-functions']

# Metadata
title: "DSC"
description: "Denver Suspension Collective"
url: "https://www.denversuspension.com"
logo: logo.jpg
favicon: /favicon.ico
timezone: America/Denver
email: denver.suspension.collective@gmail.com

# Author
author:
  name: 'Denver Suspension Collective'
  avatar: logo.jpg

# URLs
img_url: '/img/'
